#!/usr/bin/env python

# This file has been modified from its orginal sources.
#
# Copyright (c) 2012 Software in the Public Interest Inc (SPI)
# Copyright (c) 2012 David Pratt
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright (c) 2008-2012 Appcelerator Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from os import path
Import('build env module')

env.Append(CPPDEFINES=('KROLL_PYTHON_API_EXPORT', 1))

build.add_thirdparty(env, 'poco')
if build.is_osx():
    env.Append(CPPPATH=['/System/Library/Frameworks/Python.framework/Versions/Current/Headers',build.tide_include_dir])
    env.Append(FRAMEWORKS=['Python'])

elif build.is_linux():
    env.Append(CPPPATH=[
        '${PYTHON_INCLUDE}',
        '/usr/lib/python/2.7/i386-linux',
        '/usr/include/python2.7',
        build.tide_include_dir])
    env.Append(LIBS=['python${PYTHON_VERSION}'])
    env.Append(CXXFLAGS = ['-Wno-unused-but-set-variable'])

elif build.is_win32():
    env.Append(CPPPATH=[build.tp('python', 'include')])
    env.Append(LIBPATH=[build.tp('python', 'libs')])
    env.Append(LIBS=['python25'])
    env.Append(CCFLAGS = ['/MD'])

build.mark_build_target(env.SharedLibrary(
    path.join(module.dir, 'tidepython'), Glob('*.cpp')))
if build.is_win32():
    build.utils.LightWeightCopy(build.tp('python'), module.dir)
