#!/usr/bin/env python

# This file has been modified from its orginal sources.
#
# Copyright (c) 2012 Software in the Public Interest Inc (SPI)
# Copyright (c) 2012 David Pratt
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright (c) 2008-2012 Appcelerator Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TIDESDK_PLATFORM_API_EXPORT', 1))
build.add_thirdparty(env, 'poco')

if build.is_win32():
    build.add_thirdparty(env, 'cairo')
    env.Append(CCFLAGS=['/MD', '/DUNICODE', '/D_UNICODE'])
    env.Append(LIBS=['Advapi32', 'Iphlpapi', 'user32', 'shell32', 'gdi32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

elif build.is_osx():
    env.Append(FRAMEWORKS = ['AppKit', 'Cocoa'])

elif build.is_linux():
    env.ParseConfig('pkg-config --cflags --libs gdk-2.0 x11')

sources = [File('platform_module.cpp'), File('platform_binding.cpp')]
if build.is_osx():
    sources.append(File('platform_binding_%s.mm' % build.os))
else:
    sources.append(File('platform_binding_%s.cpp' % build.os))

build.mark_build_target(env.SharedLibrary(
    path.join(module.dir, 'tideplatform'), sources))
