#!/usr/bin/env python

# This file has been modified from its orginal sources.
#
# Copyright (c) 2012 Software in the Public Interest Inc (SPI)
# Copyright (c) 2012 David Pratt
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright (c) 2008-2012 Appcelerator Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from os import path
from tide import Module
Import('build')

def build_module_from_directory(dir):
    name = dir.lower().replace('.', '')
    module = Module(name, build.version, path.join(build.dir, 'modules', name))
    build.modules.append(module)

    env = build.env.Clone()
    env.Append(CPPDEFINES=[('MODULE_NAME', name), ('MODULE_VERSION', build.version)])

    SConscript(
        path.join(dir, 'SConscript'),
        variant_dir=path.join(build.dir, 'objs', 'modules', name),
        exports='build module env',
        duplicate=0)

Export('build_module_from_directory')
if not ARGUMENTS.get('lite', 0):
    for dir in ['python', 'ruby', 'php']:
        build_module_from_directory(dir)
